### ISSUE TITLE
Tutorial Doesn't Remember Session

### ISSUE THREAD

**Issue by jferragut** [breatheco-de/desktop-client#23]
**Experienced behavior:**  
- Visit Student.breatheco.de, tutorial pops up.
- Attempt to close tutorial, then use the gear to hide tutorial.
- Tutorial still pops up on different views
- On next visit, tutorial is also present

**Expected Behavior:**
- Visit Student.breatheco.de, tutorial pops up.
- Attempt to close tutorial (would be nice to have a popup that asks if you'd like to hide the tutorial)
- Use gear to hide tutorial
- Site should set a cookie that remembers your choice on hiding the tutorial
- App should check this cookie to ensure all views hide if you have selected to hide the tutorial.

**Comment by alesanchezr** [comment]
@jferragut done! It is a quick fix (reloading the website) but it works. jejeje

The ideal way will be to listen to the changes on the session, but I guess this works for now. Maybe that can me a PR for the students.
